/* Generated by JASS Version 0.1 64-bit DEBUGGING-build Copyright (c) 2016-2017 Andrew Trotman, University of Otago */
#include"query_heap.h"

using namespace JASS;
void T_6(query_heap &q);
void T_1(query_heap &q);
void T_4(query_heap &q);
void T_5(query_heap &q);
void T_3(query_heap &q);
void T_8(query_heap &q);
void T_7(query_heap &q);
void T_2(query_heap &q);
void T_9(query_heap &q);
void T_10(query_heap &q);
void T_four(query_heap &q);
void T_eight(query_heap &q);
void T_five(query_heap &q);
void T_seven(query_heap &q);
void T_two(query_heap &q);
void T_six(query_heap &q);
void T_three(query_heap &q);
void T_one(query_heap &q);
void T_nine(query_heap &q);
void T_ten(query_heap &q);
