/* Generated by JASS Version 0.1 64-bit DEBUGGING-build Copyright (c) 2016-2017 Andrew Trotman, University of Otago */
#include"query16_t.h"

using namespace JASS;
void T_6(query16_t &q);
void T_1(query16_t &q);
void T_4(query16_t &q);
void T_5(query16_t &q);
void T_3(query16_t &q);
void T_8(query16_t &q);
void T_7(query16_t &q);
void T_2(query16_t &q);
void T_9(query16_t &q);
void T_10(query16_t &q);
void T_four(query16_t &q);
void T_eight(query16_t &q);
void T_five(query16_t &q);
void T_seven(query16_t &q);
void T_two(query16_t &q);
void T_six(query16_t &q);
void T_three(query16_t &q);
void T_one(query16_t &q);
void T_nine(query16_t &q);
void T_ten(query16_t &q);
