/* Generated by JASS Version 0.1 64-bit DEBUGGING-build Copyright (c) 2016-2017 Andrew Trotman, University of Otago */
#include <stddef.h>
#include <stdint.h>
#include"query.h"

using namespace JASS;
void T_6(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(6,1);
}
void T_1(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(1,1);
}
void T_4(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(4,1);
}
void T_5(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(5,1);
}
void T_3(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(3,1);
}
void T_8(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(8,1);
}
void T_7(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(7,1);
}
void T_2(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(2,1);
}
void T_9(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(9,1);
}
void T_10(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(10,1);
}
void T_four(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_eight(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(3,1);
q.add_rsv(4,1);
q.add_rsv(5,1);
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_five(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_seven(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(4,1);
q.add_rsv(5,1);
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_two(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_six(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(5,1);
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_three(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_one(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(10,1);
}
void T_nine(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(2,1);
q.add_rsv(3,1);
q.add_rsv(4,1);
q.add_rsv(5,1);
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
void T_ten(query<uint16_t, 10'000'000, 10> &q)
{
q.add_rsv(1,1);
q.add_rsv(2,1);
q.add_rsv(3,1);
q.add_rsv(4,1);
q.add_rsv(5,1);
q.add_rsv(6,1);
q.add_rsv(7,1);
q.add_rsv(8,1);
q.add_rsv(9,1);
q.add_rsv(10,1);
}
