#!/usr/bin/env python3

import argparse
import json
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the json input")

args, unknown = parser.parse_known_args()

if args.json["collection"]["name"].lower() == "robust04":
	subprocess.run("/search_robust04 " + args.json["topic"]["path"] + " " + str(args.json["top_k"]), shell=True)
